repos:
  -   repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
          language_version: python3
  -   repo: local
      hooks:
        - id: pytest-unit-tests-check
          name: pytest-unit-tests-check
          entry: pytest --ignore=./tests/test_integration.py
          language: system
          pass_filenames: false
          always_run: true
  -   repo: local
      hooks:
        - id: pytest-integration-tests-check
          name: pytest-integration-tests-check
          entry: pytest -v ./tests/test_integration.py
          language: system
          pass_filenames: false
          always_run: true